services:
  # --- Infrastructure ---
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/config-server:${TAG:-latest}
    container_name: config-server
    restart: unless-stopped
    ports:
      - "${CF_IP:-127.0.0.1}:${CF_PORT:-3306}:${CF_PORT:-3306}"
    volumes:
      # If the service needs to read/write config files, mount a volume
      - ./config:/config
    networks:
      - teleremote-network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote-network:
    name: teleremote-network
    external: true
