services:
  config-server:
    build: .
    image: config-server:latest
    container_name: config-server
    restart: unless-stopped
    ports:
      - "1026:1026"
    environment:
      # Inject OS level variables
      - CONFIG_SERVER_PORT
      - CONFIG_SERVER_LOG_LEVEL
      - CONFIG_SERVER_DB_PATH

networks:
  default:
    name: teleremote_network
    external: true
